# Generated by Django 6.0 on 2026-01-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_consultation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="image_url",
            field=models.CharField(
                blank=True,
                default="",
                max_length=500,
                null=True,
                verbose_name="图片链接",
            ),
        ),
        migrations.AddField(
            model_name="chattopic",
            name="image_url",
            field=models.CharField(
                blank=True,
                default="",
                max_length=500,
                null=True,
                verbose_name="图片链接",
            ),
        ),
    ]
