# Generated by Django 6.0 on 2026-01-14 02:41

import django.db.models.deletion
from django.contrib.auth.hashers import make_password
from django.db import migrations, models


def create_default_user(apps, schema_editor):
    """创建默认用户，用于迁移已有数据"""
    User = apps.get_model('ai_consultation', 'User')
    if not User.objects.filter(id=1).exists():
        User.objects.create(id=1, username='default', password=make_password(None))


class Migration(migrations.Migration):

    dependencies = [
        ("ai_consultation", "0002_chatmessage_image_url_chattopic_image_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=50, unique=True, verbose_name="用户名"),
                ),
                ("password", models.CharField(max_length=50, verbose_name="密码")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
                "db_table": "ai_consultation_user",
            },
        ),
        # 创建默认用户
        migrations.RunPython(create_default_user, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="chattopic",
            name="user_id",
        ),
        migrations.AddField(
            model_name="chattopic",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topics",
                to="ai_consultation.user",
                verbose_name="用户",
            ),
        ),
    ]
